[project]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "eval"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
pyprojroot = ">=0.3.0,<0.4"
openai = ">=1.59.6,<2"
python-dotenv = ">=1.0.1,<2"
sqlalchemy = ">=2.0.37,<3"
urllib3 = ">=1.25.3,<2.1.0"
python-dateutil = ">=2.5.3"
pydantic = ">=2"
websocket-client = ">=1.6.1"
jupyterlab = ">=4.3.4,<5"
pytest = ">=8.3.4,<9"
websockets = ">=14.1,<15"

[pypi-dependencies]
cheshire-cat-api = "*"
